#!/bin/bash

set -euo pipefail

APP_NAME="NetworkAutoMount"
LAUNCH_LABEL="com.user.networkmount"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$HOME/Library/Application Support/$APP_NAME"
CONFIG_FILE="$CONFIG_DIR/config.sh"
DEFAULT_MOUNT_ROOT="$HOME/Library/Caches/$APP_NAME/mounts"
PLIST_FILE="$HOME/Library/LaunchAgents/$LAUNCH_LABEL.plist"
NSMB_CONF_FILE="$HOME/Library/Preferences/nsmb.conf"

find_wifi_device() {
    networksetup -listallhardwareports 2>/dev/null | awk '
        /Hardware Port: (Wi-Fi|AirPort)/ {
            getline
            if ($1 == "Device:") {
                print $2
                exit
            }
        }
    '
}

get_current_network() {
    local wifi_device

    wifi_device="$(find_wifi_device)"
    if [ -z "$wifi_device" ]; then
        return 0
    fi

    networksetup -getairportnetwork "$wifi_device" 2>/dev/null | sed -n 's/^Current Wi-Fi Network: //p' | tr -d '\n'
}

write_config() {
    local target_network="$1"
    local share_server="$2"
    local share_path="$3"
    local username="$4"
    local auth_mode="$5"
    local mount_root="$6"
    local show_in_finder="$7"
    local mount_name
    local mount_options="nobrowse,automounted"

    if [ "$show_in_finder" = "true" ]; then
        mount_options="automounted"
    fi

    mount_name="$(printf '%s' "$share_path" | tr '/:' '__')"

    mkdir -p "$CONFIG_DIR"
    {
        echo "#!/bin/bash"
        echo "# Generated by setup.sh"
        printf "TARGET_NETWORK=%q\n" "$target_network"
        printf "SHARE_SERVER=%q\n" "$share_server"
        printf "SHARE_PATH=%q\n" "$share_path"
        printf "USERNAME=%q\n" "$username"
        printf "AUTH_MODE=%q\n" "$auth_mode"
        printf "MOUNT_ROOT=%q\n" "$mount_root"
        printf "MOUNT_NAME=%q\n" "$mount_name"
        printf "SHOW_IN_FINDER=%q\n" "$show_in_finder"
        printf "MOUNT_OPTIONS=%q\n" "$mount_options"
    } > "$CONFIG_FILE"

    chmod 600 "$CONFIG_FILE"
}

upsert_nsmb_conf() {
    local share_server="$1"
    local share_path="$2"
    local username="$3"
    local password="$4"
    local section tmp_file

    section="[$share_server:$share_path]"
    mkdir -p "$(dirname "$NSMB_CONF_FILE")"
    touch "$NSMB_CONF_FILE"
    chmod 600 "$NSMB_CONF_FILE"

    tmp_file="$(mktemp)"
    awk -v section="$section" '
        /^\[.*\]$/ {
            if (skip) {
                skip = 0
            }
            if ($0 == section) {
                skip = 1
                next
            }
        }
        !skip {
            print
        }
    ' "$NSMB_CONF_FILE" > "$tmp_file"

    {
        cat "$tmp_file"
        printf '\n%s\n' "$section"
        printf 'username=%s\n' "$username"
        printf 'password=%s\n' "$password"
    } > "$NSMB_CONF_FILE"

    rm -f "$tmp_file"
    chmod 600 "$NSMB_CONF_FILE"
}

bootstrap_launch_agent() {
    local launch_domain

    launch_domain="gui/$(id -u)"
    launchctl bootout "$launch_domain" "$PLIST_FILE" >/dev/null 2>&1 || true
    launchctl bootstrap "$launch_domain" "$PLIST_FILE"
    launchctl kickstart -k "$launch_domain/$LAUNCH_LABEL"
}

echo "=== Network Share LaunchAgent Setup ==="
echo ""

CURRENT_NETWORK="$(get_current_network)"
if [ -n "$CURRENT_NETWORK" ]; then
    echo "Current Wi-Fi Network: $CURRENT_NETWORK"
    echo ""
fi

echo "Please provide the following information:"
echo ""

read -r -p "Target Network Name [$CURRENT_NETWORK]: " TARGET_NETWORK
TARGET_NETWORK="${TARGET_NETWORK:-$CURRENT_NETWORK}"

if [ -z "$TARGET_NETWORK" ]; then
    echo "A target network is required."
    exit 1
fi

read -r -p "Server IP/Hostname: " SHARE_SERVER
read -r -p "Share Name: " SHARE_PATH
read -r -p "Username: " USERNAME

if [ -z "$SHARE_SERVER" ] || [ -z "$SHARE_PATH" ] || [ -z "$USERNAME" ]; then
    echo "Server, share name, and username are required."
    exit 1
fi

echo ""
echo "Choose an auth mode:"
echo "  1. Store credentials in ~/Library/Preferences/nsmb.conf for unattended mounting"
echo "     This is plain-text storage protected by file permissions, not Keychain."
echo "  2. Do not store credentials (works only if macOS already has a valid SMB session)"
read -r -p "Selection [1]: " AUTH_SELECTION
AUTH_SELECTION="${AUTH_SELECTION:-1}"

AUTH_MODE="system"
case "$AUTH_SELECTION" in
    1)
        AUTH_MODE="nsmb"
        ;;
    2)
        AUTH_MODE="system"
        ;;
    *)
        echo "Invalid selection: $AUTH_SELECTION"
        exit 1
        ;;
esac

echo ""
read -r -p "Show mounted share in Finder? (y/n) [n]: " SHOW_IN_FINDER_PROMPT
SHOW_IN_FINDER="false"
case "${SHOW_IN_FINDER_PROMPT:-n}" in
    y|Y)
        SHOW_IN_FINDER="true"
        ;;
    n|N)
        SHOW_IN_FINDER="false"
        ;;
    *)
        echo "Invalid selection: ${SHOW_IN_FINDER_PROMPT:-}"
        exit 1
        ;;
esac

echo ""
echo "Configuration Summary:"
echo "  Network: $TARGET_NETWORK"
echo "  Server: $SHARE_SERVER"
echo "  Share: $SHARE_PATH"
echo "  Username: $USERNAME"
echo "  Auth Mode: $AUTH_MODE"
echo "  Show In Finder: $SHOW_IN_FINDER"
echo "  Mount Root: $DEFAULT_MOUNT_ROOT"
echo ""

read -r -p "Proceed with configuration? (y/n): " CONFIRM
if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
    echo "Setup cancelled."
    exit 0
fi

if [ "$AUTH_MODE" = "nsmb" ]; then
    echo ""
    read -r -s -p "SMB Password: " PASSWORD
    echo ""
    read -r -s -p "Confirm Password: " PASSWORD_CONFIRM
    echo ""

    if [ "$PASSWORD" != "$PASSWORD_CONFIRM" ]; then
        echo "Passwords did not match."
        exit 1
    fi

    upsert_nsmb_conf "$SHARE_SERVER" "$SHARE_PATH" "$USERNAME" "$PASSWORD"
    echo "Updated $NSMB_CONF_FILE"
fi

write_config "$TARGET_NETWORK" "$SHARE_SERVER" "$SHARE_PATH" "$USERNAME" "$AUTH_MODE" "$DEFAULT_MOUNT_ROOT" "$SHOW_IN_FINDER"
echo "Wrote config to $CONFIG_FILE"

"$SCRIPT_DIR/install.sh"

echo ""
echo "Loading LaunchAgent..."
bootstrap_launch_agent

echo "Setup complete. The LaunchAgent will now:"
echo "  - monitor network changes"
echo "  - mount the share when connected to '$TARGET_NETWORK'"
echo "  - unmount the share when disconnected"
echo "  - use mount path: $DEFAULT_MOUNT_ROOT/$(printf '%s' "$SHARE_PATH" | tr '/:' '__')"
echo ""
echo "Useful commands:"
echo "  - Check status: $SCRIPT_DIR/network_mount_enhanced.sh status"
echo "  - View logs: tail -f ~/Library/Logs/network_mount.log"
echo "  - Unload LaunchAgent: launchctl bootout gui/$(id -u) ~/Library/LaunchAgents/$LAUNCH_LABEL.plist"
